/*
 * aegis_inference.cpp - Aegis Edge on-device gesture inference (Option B core)
 * ----------------------------------------------------------------------------
 * Target : Silicon Labs Thunderboard Sense 2 (BRD4166A),
 *          EFR32MG12P332F1024GL125, Cortex-M4F @ 38.4 MHz, 256 KB RAM, NO NPU.
 * SDK    : Gecko SDK (GSDK) 4.0.2 + GNU Arm 10-2020-q4-major.
 * Lang   : C++14 (MANDATORY - the Edge Impulse SDK is C++).
 *
 * What this file does (the Option-B sensor->inference->feedback path):
 *   (a) Reads a slice of 3-axis accelerometer data into a buffer via a
 *       get_signal_data callback (EIDSP_OK contract).
 *   (b) Runs the classifier with run_classifier_continuous() to amortize DSP
 *       across slices (run_classifier_init() is called ONCE in init).
 *   (c) Finds the argmax of result.classification[].
 *   (d) Maps the winning gesture to an RGB LED color and drives the LED
 *       (BOARD_rgbledPowerEnable(true) FIRST, then BOARD_rgbledSetColor).
 *   (e) Packs {class_index:uint8, confidence:uint8 0..100} into a 2-byte buffer
 *       and notifies it on the results characteristic, GATED on CCCD subscribe,
 *       via sl_bt_gatt_server_send_notification().
 *
 *   Plus the BLE event handlers: connection_opened -> store handle;
 *   gatt_server_characteristic_status -> track client_config_flags == 2.
 *
 * ============================================================================
 *  BUILD STATUS: *** NOT COMPILED in this environment. ***
 *  No GSDK / ARM toolchain is available here. This is a correct, heavily
 *  commented integration SKELETON. Build it in Simplicity Studio 5 with
 *  GSDK 4.0.2 + GNU Arm 10-2020-q4-major, dropped into your fork of
 *  edgeimpulse/firmware-silabs-thunderboard-sense-2. See ./README.md and
 *  ../integration-notes.md.
 * ============================================================================
 *
 * Legend:
 *   [VERIFIED]          - EI C++ SDK / sl_bt API convention, stable across boards.
 *   [CONFIRM-ON-DEVICE] - board/pin/GSDK/GATT-DB/IMU-specific; validate on HW.
 */

#include "aegis_inference.h"

/* ---- Edge Impulse SDK ----------------------------------------------------
 * [VERIFIED] The C++ library export is a .zip of three folders:
 *   edge-impulse-sdk/  model-parameters/  tflite-model/
 * Unzip them into the project source tree and add to the include paths. This
 * single include pulls in run_classifier(), run_classifier_continuous(),
 * run_classifier_init(), the ei_impulse_result_t type, and ALL the
 * EI_CLASSIFIER_* macros (sizes, label count, anomaly flag). We never hardcode
 * sizes -- we always use the macros so a model re-export stays correct.
 */
#include "edge-impulse-sdk/classifier/ei_run_classifier.h"

/* ---- Silicon Labs BLE + board support ------------------------------------
 * [CONFIRM-ON-DEVICE] exact header names for your pinned GSDK 4.0.2:
 *   - sl_bt_api.h  : sl_bt_* GATT/connection API + sl_bt_msg_t + event ids.
 *   - bsp.h        : BOARD_rgbledPowerEnable / BOARD_rgbledSetColor.
 *   - gatt_db.h    : generated gattdb_* characteristic handles.
 * These are guarded so this file at least parses if a header is named slightly
 * differently on your install -- but you MUST wire the real ones for a build.
 */
#include "sl_bt_api.h"   /* [VERIFIED] GSDK 4.x sl_bt_* API (NOT old gecko_cmd_*) */
#include "bsp.h"         /* [CONFIRM-ON-DEVICE] BOARD_* RGB LED helpers          */
#include "gatt_db.h"     /* generated by the GATT Configurator: #defines the     */
                         /* gattdb_aegis_results / gattdb_aegis_control handles   */
                         /* as macros (NOT linker symbols) -- include, don't extern */

#include <string.h>      /* strcmp, memset */

/* ==========================================================================
 * Module-private state
 * ========================================================================== */

/* run_classifier_init() must run exactly once before the first continuous
 * slice. Guard so a double-init or an inference-before-init can't happen. */
static bool s_classifier_ready = false;

/* BLE connection + subscription state, owned here (see aegis_ble_on_event). */
static uint8_t s_conn_handle        = 0;      /* from connection_opened       */
static bool    s_connection_open    = false;
static bool    s_results_subscribed = false;  /* CCCD == notifications (==2)  */

/* --------------------------------------------------------------------------
 * Slice buffer for run_classifier_continuous().
 *
 * [VERIFIED] In continuous mode you feed EI_CLASSIFIER_SLICE_SIZE *raw* values
 * per call (NOT the whole DSP frame). The SDK maintains the rolling window and
 * amortizes the DSP across slices -- that's why continuous is the right choice
 * for a live IMU stream on a 38.4 MHz M4F with no NPU.
 *
 * Layout MUST match training: interleaved 3-axis accel -> accX, accY, accZ,
 * accX, accY, accZ, ...  (3-axis accelerometer ONLY -- the proven recipe on the
 * ICM-20648, NOT 6-axis.) [CONFIRM-ON-DEVICE]
 *
 * Sized purely from the EI macro -- never a magic number.
 * -------------------------------------------------------------------------- */
static float s_slice_buf[EI_CLASSIFIER_SLICE_SIZE];

/* How many valid floats are currently sitting in s_slice_buf. The IMU producer
 * (your sensor task / fifo drain) fills this; aegis_inference_step() consumes a
 * full slice and resets it. */
static volatile size_t s_slice_fill = 0;

/* ==========================================================================
 * Section A: IMU -> signal_t bridge
 * ========================================================================== */

/*
 * [CONFIRM-ON-DEVICE] PRODUCER HOOK.
 *
 * Wire this to your real ICM-20648 read path (sl_sensor / the fork's IMU
 * driver). It should append interleaved accel triples until a full slice is
 * staged, then return true so aegis_inference_step() runs one inference slice.
 *
 * This stub returns false (no data) so the build does not pretend to have a
 * sensor. Replace the body with your FIFO drain. Keep the interleave order
 * identical to how the impulse was trained.
 *
 * Returns: true when s_slice_buf holds a full EI_CLASSIFIER_SLICE_SIZE slice.
 */
static bool aegis_imu_fill_slice(void)
{
    /* EXAMPLE shape (pseudo-code) of what the real producer does:
     *
     *   while (s_slice_fill + 3 <= EI_CLASSIFIER_SLICE_SIZE &&
     *          icm20648_accel_available()) {
     *       float ax, ay, az;
     *       icm20648_read_accel_g(&ax, &ay, &az);   // [CONFIRM-ON-DEVICE units]
     *       s_slice_buf[s_slice_fill++] = ax;
     *       s_slice_buf[s_slice_fill++] = ay;
     *       s_slice_buf[s_slice_fill++] = az;
     *   }
     *   return (s_slice_fill == EI_CLASSIFIER_SLICE_SIZE);
     */
    return (s_slice_fill == EI_CLASSIFIER_SLICE_SIZE);
}

/*
 * [VERIFIED] signal_t get_data callback.
 *
 * EI calls this to pull `length` floats starting at `offset` instead of us
 * handing over a giant buffer. For a continuous SLICE the offset/length stay
 * within [0, EI_CLASSIFIER_SLICE_SIZE). MUST return EIDSP_OK on success.
 *
 * Bounds-checked: a bad offset/length returns EIDSP_OUT_OF_BOUNDS rather than
 * reading past the buffer.
 */
static int aegis_get_signal_data(size_t offset, size_t length, float *out_ptr)
{
    if (offset + length > EI_CLASSIFIER_SLICE_SIZE) {
        return EIDSP_OUT_OF_BOUNDS;
    }
    for (size_t i = 0; i < length; i++) {
        out_ptr[i] = s_slice_buf[offset + i];
    }
    return EIDSP_OK;   /* [VERIFIED] the required success code */
}

/* ==========================================================================
 * Section B: class -> color
 * ========================================================================== */

aegis_gesture_t aegis_gesture_from_label(const char *label)
{
    if (label == NULL)                  return AEGIS_GESTURE_UNKNOWN;
    if (!strcmp(label, "circle"))       return AEGIS_GESTURE_CIRCLE;
    if (!strcmp(label, "zigzag"))       return AEGIS_GESTURE_ZIGZAG;
    if (!strcmp(label, "updown"))       return AEGIS_GESTURE_UPDOWN;
    if (!strcmp(label, "leftright"))    return AEGIS_GESTURE_LEFTRIGHT;
    if (!strcmp(label, "none"))         return AEGIS_GESTURE_NONE;
    return AEGIS_GESTURE_UNKNOWN;       /* label drifted from the 5 known classes */
}

aegis_rgb_t aegis_color_for_gesture(aegis_gesture_t gesture)
{
    /* Spec mapping: circle=blue, zigzag=green, updown=red, leftright=purple,
     * none=off. [CONFIRM-ON-DEVICE] RGB byte values are taste/visibility --
     * tune on real hardware under USB power (LEDs are dark on the coin cell).
     * See the discrepancy note in aegis_inference.h vs ../integration-notes.md. */
    switch (gesture) {
        case AEGIS_GESTURE_CIRCLE:    return (aegis_rgb_t){   0,   0, 255 }; /* blue   */
        case AEGIS_GESTURE_ZIGZAG:    return (aegis_rgb_t){   0, 255,   0 }; /* green  */
        case AEGIS_GESTURE_UPDOWN:    return (aegis_rgb_t){ 255,   0,   0 }; /* red    */
        case AEGIS_GESTURE_LEFTRIGHT: return (aegis_rgb_t){ 128,   0, 128 }; /* purple */
        case AEGIS_GESTURE_NONE:                                            /* off    */
        default:                      return (aegis_rgb_t){   0,   0,   0 };
    }
}

/* Drive the RGB LED for a gesture.
 * [VERIFIED ORDER] BOARD_rgbledPowerEnable(true) is done once in init; here we
 * only set the color. Setting a color without the rail powered shows nothing. */
static void aegis_drive_led(aegis_gesture_t gesture)
{
    aegis_rgb_t c = aegis_color_for_gesture(gesture);
    BOARD_rgbledSetColor(c.r, c.g, c.b);  /* [CONFIRM-ON-DEVICE] arg order r,g,b */
}

/* ==========================================================================
 * Section C: BLE notify (gated on CCCD subscribe)
 * ========================================================================== */

/* True only when a central is connected AND has turned on notifications. */
bool aegis_ble_results_subscribed(void)
{
    return s_connection_open && s_results_subscribed;
}

/*
 * Pack {class_index, confidence%} into 2 bytes and notify the results char.
 * No-op unless a client is subscribed (CCCD == notifications). [VERIFIED] the
 * sl_bt_gatt_server_send_notification signature is
 *   (uint8_t connection, uint16_t characteristic, size_t value_len,
 *    const uint8_t *value).
 */
static void aegis_notify_result(aegis_gesture_t gesture, uint8_t confidence_pct)
{
    if (!aegis_ble_results_subscribed()) {
        return;  /* gate: do not notify an unsubscribed/absent client */
    }

    /* 2-byte payload, matches AEGIS_RESULTS_PAYLOAD_LEN and the dashboard's
     * defensive parser: [class_index][confidence 0..100]. */
    uint8_t payload[AEGIS_RESULTS_PAYLOAD_LEN];
    payload[0] = (uint8_t)gesture;            /* 0..4 (or 0xFF if UNKNOWN)      */
    payload[1] = confidence_pct;              /* already saturated to 0..100    */

    sl_status_t st = sl_bt_gatt_server_send_notification(
        s_conn_handle,
        gattdb_aegis_results,                 /* [CONFIRM-ON-DEVICE] gattdb id   */
        AEGIS_RESULTS_PAYLOAD_LEN,
        payload);

    /* [CONFIRM-ON-DEVICE] On a busy link this can return SL_STATUS_NO_MORE_RESOURCE
     * (TX buffer full). Drop the sample (next slice will send a fresh result) --
     * do NOT block the inference loop retrying. Optionally count drops for the
     * benchmark/diagnostics. */
    (void)st;
}

/* ==========================================================================
 * Section D: inference step (the heart of the loop)
 * ========================================================================== */

/* Saturate an EI confidence (0.0 .. 1.0 float) to a 0..100 percent uint8. */
static uint8_t aegis_conf_to_pct(float v)
{
    if (v <= 0.0f)   return 0;
    if (v >= 1.0f)   return 100;
    /* +0.5 to round to nearest rather than truncate. */
    return (uint8_t)((v * 100.0f) + 0.5f);
}

void aegis_inference_step(void)
{
    /* Guard: never infer before run_classifier_init(). */
    if (!s_classifier_ready) {
        return;
    }

    /* Only run when a full slice is staged. */
    if (!aegis_imu_fill_slice()) {
        return;
    }

    /* --- build the signal over the staged slice ---------------------------
     * [VERIFIED] For continuous mode signal.total_length MUST EXACTLY equal
     * EI_CLASSIFIER_SLICE_SIZE (mismatch -> EI_IMPULSE_INVALID_SIZE).
     * We size from the macro so this stays true after any model re-export. */
    signal_t signal;
    signal.total_length = EI_CLASSIFIER_SLICE_SIZE;
    signal.get_data     = &aegis_get_signal_data;

    ei_impulse_result_t result;
    memset(&result, 0, sizeof(result));

    /* [VERIFIED] run_classifier_continuous(&signal, &result, debug=false).
     * Continuous amortizes the DSP across slices -- the right call for a live
     * IMU stream on this MCU. The 3rd arg is the debug-print flag. */
    EI_IMPULSE_ERROR err = run_classifier_continuous(&signal, &result, false);

    /* Slice consumed -- reset the producer's fill so the next slice accumulates
     * cleanly even if we bail below. */
    s_slice_fill = 0;

    if (err != EI_IMPULSE_OK) {
        /* Do NOT act on a failed inference. [CONFIRM-ON-DEVICE] route `err` to
         * your log (ei_printf / SEGGER RTT) while bringing up the board. */
        return;
    }

    /* --- argmax over result.classification[] ------------------------------
     * [VERIFIED] result.classification[ix] has .label (const char*) and
     * .value (float), ix in 0 .. EI_CLASSIFIER_LABEL_COUNT-1, ordered as the
     * model was trained. */
    size_t best = 0;
    for (size_t ix = 1; ix < EI_CLASSIFIER_LABEL_COUNT; ix++) {
        if (result.classification[ix].value > result.classification[best].value) {
            best = ix;
        }
    }
    const char *best_label = result.classification[best].label;
    float       best_value = result.classification[best].value;

    /* Resolve the model label string back to our stable enum so the BLE wire
     * index never drifts from the firmware's internal class ids. */
    aegis_gesture_t gesture = aegis_gesture_from_label(best_label);

#if EI_CLASSIFIER_HAS_ANOMALY == 1
    /* [VERIFIED] result.anomaly is the K-means anomaly score (higher = more
     * out-of-distribution). [CONFIRM-ON-DEVICE] choose a threshold; a high
     * anomaly should probably force NONE/off so a weird motion is not reported
     * as a confident gesture. */
    if (result.anomaly > AEGIS_ANOMALY_THRESHOLD) {
        gesture    = AEGIS_GESTURE_NONE;
        best_value = 0.0f;
    }
#endif

    /* --- confidence gate --------------------------------------------------
     * [CONFIRM-ON-DEVICE] tune this. Below the gate we report/show NONE rather
     * than flicker between low-confidence classes. */
    if (best_value < AEGIS_CONFIDENCE_GATE) {
        gesture    = AEGIS_GESTURE_NONE;
        best_value = 0.0f;
    }

    uint8_t conf_pct = aegis_conf_to_pct(best_value);

    /* (d) LED feedback (USB power only -- dark on the coin cell). */
    aegis_drive_led(gesture);

    /* (e) BLE notify {class_index, confidence%}, gated on CCCD subscribe. */
    aegis_notify_result(gesture, conf_pct);

    /* --- timing (the benchmark deliverable) -------------------------------
     * [VERIFIED] result.timing.dsp / .classification are in ms. Capture these
     * for ../benchmark/. [CONFIRM-ON-DEVICE] surface them over RTT or a debug
     * BLE characteristic during bring-up. */
    (void)result.timing.dsp;
    (void)result.timing.classification;
}

/* ==========================================================================
 * Section E: init
 * ========================================================================== */

bool aegis_inference_init(void)
{
    /* [VERIFIED ORDER] power the RGB rail FIRST -- LEDs are dark without it.
     * [CONFIRM-ON-DEVICE] the LEDs draw too much for the CR2032 coin cell; this
     * is only visible on USB power. */
    BOARD_rgbledPowerEnable(true);
    BOARD_rgbledSetColor(0, 0, 0);   /* start dark */

    /* [VERIFIED] run_classifier_init() exactly once before the first
     * run_classifier_continuous() slice. It allocates the rolling-window /
     * continuous DSP state. */
    run_classifier_init();

    s_slice_fill        = 0;
    s_classifier_ready  = true;
    return true;
}

/* ==========================================================================
 * Section F: BLE event handlers
 *
 * [VERIFIED] Forward every event from the GSDK-generated single
 * sl_bt_on_event() dispatcher into here. We track:
 *   connection_opened           -> store the connection handle.
 *   connection_closed           -> clear connection + subscription state.
 *   gatt_server_characteristic_status with status == client_config
 *                               -> subscription is on iff client_config_flags
 *                                  == sl_bt_gatt_notification (value 2).
 * Do NOT use the old v2.x gecko_cmd_* API.
 * ========================================================================== */
void aegis_ble_on_event(void *evt_void)
{
    sl_bt_msg_t *evt = (sl_bt_msg_t *)evt_void;
    if (evt == NULL) {
        return;
    }

    switch (SL_BT_MSG_ID(evt->header)) {

    case sl_bt_evt_connection_opened_id:
        /* [VERIFIED] track the connection handle for notifications. */
        s_conn_handle     = evt->data.evt_connection_opened.connection;
        s_connection_open = true;
        break;

    case sl_bt_evt_connection_closed_id:
        /* Link gone -- forget everything so we can't notify a stale handle. */
        s_connection_open    = false;
        s_results_subscribed = false;
        break;

    case sl_bt_evt_gatt_server_characteristic_status_id: {
        const sl_bt_evt_gatt_server_characteristic_status_t *st =
            &evt->data.evt_gatt_server_characteristic_status;

        /* Only care about CCCD (client config) changes on OUR results char. */
        if (st->characteristic == gattdb_aegis_results &&
            st->status_flags    == (uint8_t)sl_bt_gatt_server_client_config) {
            /* [VERIFIED] client_config_flags == 2 (sl_bt_gatt_notification)
             * means the central enabled notifications. */
            s_results_subscribed =
                (st->client_config_flags == (uint16_t)sl_bt_gatt_notification);
        }
        break;
    }

    default:
        /* Other events (advertising, GATT writes to the control char, etc.)
         * are handled by the app shell / other modules. [CONFIRM-ON-DEVICE]
         * if you want this module to also honor control-char 0x01/0x00
         * start/stop, handle sl_bt_evt_gatt_server_attribute_value_id for
         * gattdb_aegis_control here. */
        break;
    }
}
